# OpenAI secrets
OPENAI_API_KEY = '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'

# Astra DB secrets
ASTRA_API_ENDPOINT = 'https://2bfc7493-b498-4bc7-aa05-3abe2c652852-us-east-2.apps.astra.datastax.com'
ASTRA_TOKEN = 'AstraCS:DRLQThntHZWoClfkxzMxCUIN:c26bc2e02e55c345330bcd2e4b78b445f60066ed8765ccd732b79f57fa0604c5'

# Jina secrets
JINA_API_KEY = 'jina_99564547804440b6b5e1fb3cd2cbe6fe6Chir4aZwMcAk9XzW8FpphhgUSij'
